// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Tripfinity.Models.Data;

#nullable disable

namespace _Tripfinity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610114741_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_Tripfinity.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusTripId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_Tripfinity.Models.BusTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BusTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 40,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 5000m,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 40,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Jigawa",
                            From = "Lagos",
                            IsActive = true,
                            Price = 5000m,
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.RailwayBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RailwayTripId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RailwayTripId");

                    b.HasIndex("UserId");

                    b.ToTable("RailwayBookings");
                });

            modelBuilder.Entity("_Tripfinity.Models.RailwayTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RailwayTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 100,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 9000m,
                            Route = "AKTS",
                            TotalSeats = 100,
                            TrainClass = "First"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 150,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 6500m,
                            Route = "AKTS",
                            TotalSeats = 150,
                            TrainClass = "Business"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 200,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 20, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 3600m,
                            Route = "AKTS",
                            TotalSeats = 200,
                            TrainClass = "Regular"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 200,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            From = "Kaduna",
                            IsActive = true,
                            Price = 3600m,
                            Route = "AKTS",
                            TotalSeats = 200,
                            TrainClass = "Regular"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 300,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 3000m,
                            Route = "Lagos-Ibadan",
                            TotalSeats = 300,
                            TrainClass = "Regular"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 300,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Lagos",
                            From = "Ibadan",
                            IsActive = true,
                            Price = 3000m,
                            Route = "Lagos-Ibadan",
                            TotalSeats = 300,
                            TrainClass = "Regular"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 250,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Itakpe",
                            From = "Warri",
                            IsActive = true,
                            Price = 2500m,
                            Route = "Warri-Itakpe",
                            TotalSeats = 250,
                            TrainClass = "Regular"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 250,
                            CreatedAt = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Warri",
                            From = "Itakpe",
                            IsActive = true,
                            Price = 2500m,
                            Route = "Warri-Itakpe",
                            TotalSeats = 250,
                            TrainClass = "Regular"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_Tripfinity.Models.Booking", b =>
                {
                    b.HasOne("_Tripfinity.Models.BusTrip", "BusTrip")
                        .WithMany()
                        .HasForeignKey("BusTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_Tripfinity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_Tripfinity.Models.RailwayBooking", b =>
                {
                    b.HasOne("_Tripfinity.Models.RailwayTrip", "RailwayTrip")
                        .WithMany()
                        .HasForeignKey("RailwayTripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_Tripfinity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RailwayTrip");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
