// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Tripfinity.Models.Data;

#nullable disable

namespace _Tripfinity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629125259_NewUpdates")]
    partial class NewUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_Tripfinity.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BusTripId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RailwayTripId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TaxiTripId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTripId");

                    b.HasIndex("RailwayTripId");

                    b.HasIndex("TaxiTripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_Tripfinity.Models.BusTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BusTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 45,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 4500m,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 50,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Benin",
                            From = "Lagos",
                            IsActive = true,
                            Price = 8500m,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 48,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            From = "Lagos",
                            IsActive = true,
                            Price = 12000m,
                            TotalSeats = 48
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 50,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 27, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Port Harcourt",
                            From = "Lagos",
                            IsActive = true,
                            Price = 10500m,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 40,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 28, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kano",
                            From = "Lagos",
                            IsActive = true,
                            Price = 15000m,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 45,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 24, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 3500m,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 42,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Jos",
                            From = "Abuja",
                            IsActive = true,
                            Price = 4200m,
                            TotalSeats = 42
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 50,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 27, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Enugu",
                            From = "Abuja",
                            IsActive = true,
                            Price = 7500m,
                            TotalSeats = 50
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 30,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 25, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Aba",
                            From = "Port Harcourt",
                            IsActive = true,
                            Price = 2800m,
                            TotalSeats = 30
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 40,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 28, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Calabar",
                            From = "Port Harcourt",
                            IsActive = true,
                            Price = 5500m,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 35,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Asaba",
                            From = "Benin",
                            IsActive = true,
                            Price = 3200m,
                            TotalSeats = 35
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 36,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 27, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Katsina",
                            From = "Kano",
                            IsActive = true,
                            Price = 3800m,
                            TotalSeats = 36
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 45,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Lagos",
                            From = "Ibadan",
                            IsActive = true,
                            Price = 4500m,
                            TotalSeats = 45
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 40,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Owerri",
                            From = "Ibadan",
                            IsActive = true,
                            Price = 6800m,
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 42,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            From = "Jos",
                            IsActive = true,
                            Price = 4200m,
                            TotalSeats = 42
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.RailwayTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RailwayTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 280,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 24, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 3000m,
                            Route = "Lagos–Ibadan",
                            TotalSeats = 280,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 280,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 24, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Lagos",
                            From = "Ibadan",
                            IsActive = true,
                            Price = 3000m,
                            Route = "Lagos–Ibadan",
                            TotalSeats = 280,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 100,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 9000m,
                            Route = "Abuja–Kaduna",
                            TotalSeats = 100,
                            TrainClass = "First"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 100,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            From = "Kaduna",
                            IsActive = true,
                            Price = 9000m,
                            Route = "Abuja–Kaduna",
                            TotalSeats = 100,
                            TrainClass = "First"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSeats = 240,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Itakpe",
                            From = "Warri",
                            IsActive = true,
                            Price = 2500m,
                            Route = "Warri–Itakpe",
                            TotalSeats = 240,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSeats = 240,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Warri",
                            From = "Itakpe",
                            IsActive = true,
                            Price = 2500m,
                            Route = "Warri–Itakpe",
                            TotalSeats = 240,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSeats = 80,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 5800m,
                            Route = "Lagos–Ibadan",
                            TotalSeats = 80,
                            TrainClass = "Business"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSeats = 95,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Kaduna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 6500m,
                            Route = "Abuja–Kaduna",
                            TotalSeats = 95,
                            TrainClass = "Business"
                        },
                        new
                        {
                            Id = 9,
                            AvailableSeats = 160,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 27, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Aba",
                            From = "Port Harcourt",
                            IsActive = true,
                            Price = 2000m,
                            Route = "Port Harcourt–Aba",
                            TotalSeats = 160,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 10,
                            AvailableSeats = 160,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 27, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Port Harcourt",
                            From = "Aba",
                            IsActive = true,
                            Price = 2000m,
                            Route = "Port Harcourt–Aba",
                            TotalSeats = 160,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 11,
                            AvailableSeats = 180,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 28, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abeokuta",
                            From = "Lagos",
                            IsActive = true,
                            Price = 1500m,
                            Route = "Lagos–Abeokuta",
                            TotalSeats = 180,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 12,
                            AvailableSeats = 180,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Lagos",
                            From = "Abeokuta",
                            IsActive = true,
                            Price = 1500m,
                            Route = "Lagos–Abeokuta",
                            TotalSeats = 180,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 13,
                            AvailableSeats = 200,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Minna",
                            From = "Abuja",
                            IsActive = true,
                            Price = 2800m,
                            Route = "Abuja–Minna",
                            TotalSeats = 200,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 14,
                            AvailableSeats = 200,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 29, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Abuja",
                            From = "Minna",
                            IsActive = true,
                            Price = 2800m,
                            Route = "Abuja–Minna",
                            TotalSeats = 200,
                            TrainClass = "Standard"
                        },
                        new
                        {
                            Id = 15,
                            AvailableSeats = 48,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 6, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            Price = 7500m,
                            Route = "Lagos–Ibadan",
                            TotalSeats = 48,
                            TrainClass = "First"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.TaxiTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaxiTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Victoria Island",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Ikeja",
                            PickupTime = new DateTime(2026, 6, 24, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Lekki",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Ikeja",
                            PickupTime = new DateTime(2026, 6, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Ikeja",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Lekki",
                            PickupTime = new DateTime(2026, 6, 25, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 10000m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Ikeja",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Victoria Island",
                            PickupTime = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12000m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Garki",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Abuja CBD",
                            PickupTime = new DateTime(2026, 6, 26, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4500m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Wuse",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Garki",
                            PickupTime = new DateTime(2026, 6, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3500m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Maitama",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Wuse",
                            PickupTime = new DateTime(2026, 6, 27, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4000m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Rumuokoro",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Port Harcourt",
                            PickupTime = new DateTime(2026, 6, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5000m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Sabon Gari",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Kano",
                            PickupTime = new DateTime(2026, 6, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3000m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Mokola",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Ibadan",
                            PickupTime = new DateTime(2026, 6, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3500m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Ugbowo",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Benin",
                            PickupTime = new DateTime(2026, 6, 29, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4000m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "New Haven",
                            IsActive = true,
                            MaxPassengers = 4,
                            PickupLocation = "Enugu",
                            PickupTime = new DateTime(2026, 6, 29, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3800m
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TripTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ValidatedByMarshalId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("_Tripfinity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailConfirmationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserWalletId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_Tripfinity.Models.Booking", b =>
                {
                    b.HasOne("_Tripfinity.Models.BusTrip", "BusTrip")
                        .WithMany()
                        .HasForeignKey("BusTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.RailwayTrip", "RailwayTrip")
                        .WithMany()
                        .HasForeignKey("RailwayTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.Tables.TaxiTrip", "TaxiTrip")
                        .WithMany()
                        .HasForeignKey("TaxiTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTrip");

                    b.Navigation("RailwayTrip");

                    b.Navigation("TaxiTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Ticket", b =>
                {
                    b.HasOne("_Tripfinity.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
