// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _Tripfinity.Models.Data;

#nullable disable

namespace _Tripfinity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727063714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_Tripfinity.Models.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BusTripId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RailwayTripId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("TaxiTripId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransportType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusTripId");

                    b.HasIndex("RailwayTripId");

                    b.HasIndex("TaxiTripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.BusTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MarshalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarshalId");

                    b.ToTable("BusTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 45,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 7, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            MarshalId = 101,
                            Price = 4500m,
                            TotalSeats = 45,
                            VehicleId = "VEH-BUS-A1B2C3D4"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 50,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 7, 7, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Benin",
                            From = "Lagos",
                            IsActive = true,
                            MarshalId = 101,
                            Price = 8500m,
                            TotalSeats = 50,
                            VehicleId = "VEH-BUS-A1B2C3D4"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.RailwayTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MarshalId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarshalId");

                    b.ToTable("RailwayTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 280,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new DateTime(2026, 7, 6, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Ibadan",
                            From = "Lagos",
                            IsActive = true,
                            MarshalId = 102,
                            Price = 3000m,
                            Route = "Lagos–Ibadan",
                            TotalSeats = 280,
                            TrainClass = "Standard",
                            VehicleId = "VEH-RAIL-X9Y8Z7W6"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.TaxiTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MarshalId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("int");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MarshalId");

                    b.ToTable("TaxiTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DropoffLocation = "Victoria Island",
                            IsActive = true,
                            MarshalId = 103,
                            MaxPassengers = 4,
                            PickupLocation = "Ikeja",
                            PickupTime = new DateTime(2026, 7, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12000m,
                            VehicleId = "VEH-TAXI-P5Q6R7S8"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodeBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("TicketReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TransportType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateTime>("TripTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ValidatedByMarshalId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TicketReference")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmationTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EmailConfirmationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserWalletId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "busmarshal@tripfinity.com",
                            FirstName = "Bus",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "Marshal",
                            LicenseId = "BUS-LIC-001",
                            PasswordHash = "Welcome123",
                            PhoneNumber = "08010000001",
                            Role = "Marshal",
                            UserWalletId = "WALLET-BUS-M001",
                            VehicleId = "VEH-BUS-A1B2C3D4",
                            VehicleType = "Bus"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "railwaymarshal@tripfinity.com",
                            FirstName = "Railway",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "Marshal",
                            LicenseId = "RAIL-LIC-001",
                            PasswordHash = "Welcome123",
                            PhoneNumber = "08010000002",
                            Role = "Marshal",
                            UserWalletId = "WALLET-RAIL-M001",
                            VehicleId = "VEH-RAIL-X9Y8Z7W6",
                            VehicleType = "Railway"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taximarshal@tripfinity.com",
                            FirstName = "Taxi",
                            IsActive = true,
                            IsEmailConfirmed = true,
                            LastName = "Marshal",
                            LicenseId = "TAXI-LIC-001",
                            PasswordHash = "Welcome123",
                            PhoneNumber = "08010000003",
                            Role = "Marshal",
                            UserWalletId = "WALLET-TAXI-M001",
                            VehicleId = "VEH-TAXI-P5Q6R7S8",
                            VehicleType = "Taxi"
                        });
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Booking", b =>
                {
                    b.HasOne("_Tripfinity.Models.Tables.BusTrip", "BusTrip")
                        .WithMany()
                        .HasForeignKey("BusTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.Tables.RailwayTrip", "RailwayTrip")
                        .WithMany()
                        .HasForeignKey("RailwayTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.Tables.TaxiTrip", "TaxiTrip")
                        .WithMany()
                        .HasForeignKey("TaxiTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("_Tripfinity.Models.Tables.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusTrip");

                    b.Navigation("RailwayTrip");

                    b.Navigation("TaxiTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.BusTrip", b =>
                {
                    b.HasOne("_Tripfinity.Models.Tables.User", null)
                        .WithMany("BusTrips")
                        .HasForeignKey("MarshalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.RailwayTrip", b =>
                {
                    b.HasOne("_Tripfinity.Models.Tables.User", null)
                        .WithMany("RailwayTrips")
                        .HasForeignKey("MarshalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.TaxiTrip", b =>
                {
                    b.HasOne("_Tripfinity.Models.Tables.User", null)
                        .WithMany("TaxiTrips")
                        .HasForeignKey("MarshalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.Ticket", b =>
                {
                    b.HasOne("_Tripfinity.Models.Tables.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("_Tripfinity.Models.Tables.User", b =>
                {
                    b.Navigation("BusTrips");

                    b.Navigation("RailwayTrips");

                    b.Navigation("TaxiTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
